services:
  rosdb:
    image: postgres:15.3-alpine
    container_name: rosdb
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - rosskerynet
    env_file:
      - dbp.env
    ports:
      - "5455:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - rskpgdata:/var/lib/postgresql/data
      - rskpgconf:/etc/postgresql
      - rskpglog:/var/log/postgresql

  valset:
    image: valkey/valkey:7.2-alpine
    container_name: valset
    networks:
      - rosskerynet
    restart: unless-stopped
    labels:
      - traefik.enable=false
    ports:
      - "6379:6379"
    env_file:
      - vlp.env
    command: valkey-server --save 20 1 --loglevel warning --aclfile /etc/redis/aclfile
    volumes:
      - rskset:/data
      - ./default.acl:/etc/redis/aclfile # Mount the ACL file

  rosskery:
    depends_on: [valset, rosdb]
    container_name: rosskery
    image: rosskery
    restart: unless-stopped
    labels:
      - traefik.http.routers.rosskery.rule=Host(`rosskery.dmz.urx.ink`)
      - traefik.http.routers.rosskery.entrypoints=web,websecure
      - traefik.http.routers.rosskery.service=rosskery
      - traefik.http.services.rosskery.loadbalancer.server.port=8078
      - traefik.http.routers.rosskery.tls=true
      - traefik.http.routers.rosskery.tls.certresolver=le
      - traefik.http.middlewares.forwardedheaders.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forwardedheaders.headers.customrequestheaders.X-Forwarded-For={ip}
      - traefik.http.routers.rosskery.middlewares=forwardedheaders
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade
      - traefik.http.routers.rosskery.middlewares=websocket-headers
      - traefik.port=80
    networks:
      - rosskerynet
      - proxy
    ports:
      - 8078:8078
    volumes:
      - rskstatic:/go/bin/static/products

networks:
  proxy:
    external: true
  rosskerynet:
    driver: bridge
    external: false

volumes:
  rskpgdata:
    driver: local
  rskpgconf:
    driver: local
  rskpglog:
    driver: local
  rskset:
    driver: local
  rskstatic:
    driver: local
