version: "3.7"

services:
  valset:
    image: valkey/valkey:7.2-alpine
    container_name: valset
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - vlp.env
    command: valkey-server --save 20 1 --loglevel warning --aclfile /etc/redis/aclfile
    volumes:
      - rskset:/data
      - ./default.acl:/etc/redis/aclfile # Mount the ACL file
volumes:
  rskset:
    driver: local
